### PR TITLE
Support for ContextPath

### PR DESCRIPTION
**Pull request by sks**
- Buildpack would automatically detect the contextPath and add the location block accordingly.
- Could use some more cleanup and I believe the logic to get the ContextPath could be part of the https://github.com/cloudfoundry/libbuildpack repo.

* A short explanation of the proposed change:
When the users have ` context-path ` in route the directive ` location / ` won't work as expected.
So we should honor the contextPath information and come up ` location ` directive accordingly.

* An explanation of the use cases your change solves

if the ` manifest.yml` have [route](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#routes) information like 
```
routes:
    - route: hostname.domain.com/contextpath
```

the  nginx.conf should know about this so that it can serve the files properly.

* [x] I have made this pull request to the `develop` branch

* [x] I have viewed signed and have submitted the Contributor License Agreement
Should have 
* [ ] I have added an integration test
Nope, Not so familiar with Ruby 😢 , Would have loved to do it, but the fact that I've to have the whole bosh-lite and cf-release run on my local pulled me off.  (Will try to write this , if this proposal seems good)

Have written couple of unit tests and deployed an application using the code from my repo.
```
buildpack: https://github.com/sks/staticfile-buildpack#feature/support_for_context_path
```

NB: The changes are  more readable if read with [ignoring whitespace changes](https://github.com/cloudfoundry/staticfile-buildpack/pull/105/files?w=1)

### CODE REVIEW

**Comment by sclevine** [comment]
This looks awesome! We need to make sure that this won't break existing apps before we merge. I'll have the team take a look very soon.

**Comment by sks** [comment]
Spoke too soon, there is a regression on this, I will update the PR once I have a solid way of doing this,

A little confused on using ` root ` or ` alias ` directive in nginx

**Comment by sclevine** [comment]
Sorry for the delay! 

We have a few concerns here:
1. This can't be enabled by default, because it will break apps that have context paths and use the current methods of accomplishing this or similar things (directories or `location_include`).
2. This seems inflexible and specific to a single use case. Do most people really want to host the same content at each route?

**Comment by sks** [comment]
Gonna close this PR, 

Not sure how much flexible is gonna be flexible enough 😢 ?

For anyone interested in how to do this using ERB

```
<%
  require 'json'
  require 'uri'

  app =  JSON.parse!(ENV["VCAP_APPLICATION"])
  uri = URI.parse('https://'+app["application_uris"][0])
  contextPath=uri.path
%>
...
location <%= contextPath %>/ {
    alias    <%= contextPath %>/ public;
....
}



For

**Comment by lnhrdt** [comment]
Hey my team is encountering a need for this type of functionality (a staticfiles app deployed to a route that's not the root). If this PR wasn't accepted, what's the recommended way to accomplish this?

**Pull request closed without merging**
