### PR TITLE
Removed nginx version display

### PR DESCRIPTION
**Pull request by shawn-nielsen**
Added server_tokens off configuration to remove nginx version on error pages to conform with security best practices and improve asthetics.

### CODE REVIEW

**Comment by shawn-nielsen** [comment]
I wasn't visible before in our github organization, but I have since change visibility to public.   How do I update the CLA status?

**Comment by flavorjones** [comment]
@shawn-nielsen - I've verified that `lds-cf` is on the approved list of organizations, so we're good with the CLA.

**Comment by flavorjones** [comment]
LGTM! I'll schedule review by the team and then merging.

Thanks so much for your contribution!

**Comment by aemengo** [comment]
Thank you very much for the submission! It has been reviewed and merged into our code base. You can expect to see it live in the upcoming release of the static-file buildpack. https://github.com/cloudfoundry/staticfile-buildpack/commit/aa5e5b3817e1c69aa78acc0414393b25d7d70b86

**Comment by flavorjones** [comment]
This should be in 1.1.2 when it drops. Thank you again!

**Pull request closed without merging**
