### PR TITLE
allow test helpers to be run on MacOS

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by sclevine** [comment]
Duplicate of #119.

@idoru do we want to support running tests outside of cflinuxfs2? If the unit tests don't rely on the environment, this seems reasonable.

**Comment by drnic** [comment]
@sclevine @idoru I think it's useful to you if contributors of this (and any buildpack we subsequently merge this into) can run the tests for themselves before submitting PRs

**Comment by sclevine** [comment]
You can currently run the tests yourself from the cloudfoundry/cflinuxfs2 Docker image available on Dockerhub. The BAL tests don't pass when run outside of that image, but these (probably) do.

**Comment by dgodd** [comment]
@drnic @sclevine This commit has two changes and my comments are seperate

1. Changing readlink to your suggestion is probably good ; it has limitations where it doesn't work as well but that is probably better than failing on macosx.

2. `source .envrc` I would rather not have. We already tell people to do that in the README, and sourcing again is something I would rather not do. (As an aside, I strongly recommend direnv, also mentioned in the README)

**Comment by drnic** [comment]
Going to close until I come back to this.

**Comment by dgodd** [comment]
@drnic We have actually just merged a mix of your suggestions and https://github.com/cloudfoundry/staticfile-buildpack/issues/118

**Comment by drnic** [comment]
Ok lovely, thx

________________________________

**Pull request closed without merging**
