### PR TITLE
Don't copy a folder named nginx to public

### PR DESCRIPTION
**Pull request by acvwilson**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
This changes `location_include` workflows to regain control over root folder naming. Freeing users from the `public/` requirement.

* An explanation of the use cases your change solves
This change adds nginx to the list of files not to be copied during push and compile.

* [x] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by acvwilson** [comment]
@sclevine Thanks for the feedback.

1. You're totally right. Added an integration test to indicate that flexibility.

1. Totally worth noting.

**Comment by sclevine** [comment]
Reviewing this PR, I noticed that `root: public` and `root: some-other-dir` behave differently. When `root: public` is specified, all files in `public` are hosted. When `root: some-other-dir` is specified, certain files aren't hosted. (This isn't a change in behavior -- just made more obvious by this PR.)

The warning about `root: /` and `location_include` needs to be removed, because it is no longer applicable. 

@idoru any thoughts about this PR?

**Comment by idoru** [comment]
@sclevine agree about removing the warning you linked.
Otherwise, I think this makes for less surprises for someone pushing apps, even if we have to mention that we're no longer copying `nginx`!

**Comment by sclevine** [comment]
@acvwilson We are willing to merge this. Are you able to remove the warning?

**Comment by Ben16** [comment]
We've removed the warning and added @acvwilson's changes.

Closing this PR as the changes were added via a rebase.

**Pull request closed without merging**
