### PR TITLE
Add HSTS option

### PR DESCRIPTION
**Pull request by dlapiduz**
Create an env variable to set the `Strict-Transport-Security` setting for Nginx.

### CODE REVIEW

**Comment by flavorjones** [comment]
Hi,

Thanks for sending this PR! Please make sure you've met the CLA requirements, as @cfdreddbot noted above.

I like the idea of adding support for HSTS, however I'd like to discuss the specifics of the proposed contribution. Some of these answers will probably relate to your specific use case, and of course I'd like to know more about what your goals are.

__Default behavior__:
Is there any reason not to make this the default behavior for static sites? I'm not a security expert, but reading the [wikipedia page](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and the [RFC](https://tools.ietf.org/html/rfc6797), it's not obvious what downsides, if any, there are to always presenting this header.

If we choose to make it the default behavior, then do we even need to present a configuration option (to turn it off)?


__Configuration mechanism__:
I'm generally opposed to introducing new environment variables for buildpack-specific configuration options. Specifically in the case of `staticfile-buildpack`, since developers need to create a `Staticfile` in their application directory, I'd like to make that the place to configure its behavior. Is there a compelling reason to do this via environment variables (e.g., multiple deployments of the same app with different configuration)?


__Tests__:
If we are indeed going to make it a configurable option, then we'll need to have some test coverage for the option before making it part of the official buildpack. The testing methodology this buildpack uses is pretty straightforward:

* create a fixture app demonstrating how the option is turned on (or off) in `cf_spec/fixtures`
* write an rspec test in `cf_spec/integration`

The CF buildpacks team is happy to provide some assistance here if you're unfamiliar with rspec or machete.

**Comment by dlapiduz** [comment]
@flavorjones you are right, it seems that adding the header would be ignored over an HTTP connection so it should break compatibility with anyone running non encrypted connections.

We can change it to a configurable option in the `Staticfile` file, that should make things more declarative and easier to use so I am all for it.

I haven't done any testing for buildpacks but I am happy to dig in.

Would you rather do the configurable option or just add it by default?

**Comment by jpluscplusm** [comment]
> Is there any reason not to make this the default behavior for static sites? 

Absolutely it should not be the default behaviour. The browser behaviour it forces, taken alongside the expiry setting a long way in the future, is much too sticky and un-turn-off-able to be a sane default. IMHO.

Once an absolutely correct setup has been proved for a site by a developer, there is an argument for turning this on. However, the behaviour that a single accidental page load over the "wrong" protocol can set a (fairly) immutable flag on the client-side means it is unsuitable to be a default setting. Again, IMHO :-)

**Comment by flavorjones** [comment]
@jpluscplusm Thanks for your comment! Reading up a bit more about the browser behavior, I think you're probably right that it shouldn't be the default.

I'd like to propose an alternative to this PR, then:

* the `Staticfile` will support a new key, "hsts", whose value will default to "false".
* app devs may set "hsts: true" in their application's `Staticfile` to have nginx emit this header.

WDYT?

**Comment by dlapiduz** [comment]
I am closing this for now... We can re implement with a `Staticfile` setting

**Comment by flavorjones** [comment]
@dlapiduz - I'm happy to have someone from the Buildpacks team work with you on this, as well -- I think it's a valuable feature. Feel free to reach out directly if you like: mdalessio@pivotal.io.

**Comment by jpluscplusm** [comment]
I agree it should be user-configurable, and a `Staticfile` setting looks like the right place.
I would suggest that the setting be more obviously-named than just `hsts`, so that someone doing a "what does this do?" test cycle doesn't invoke the hard-to-shift client-side behaviour.

**Pull request closed without merging**
